name: Build LaTeX document

on:
  push:
    branches: [ main , 'release/*' , 'test/*' ]
  pull_request:
    branches: [ main , 'release/*']
  workflow_dispatch: {}  # Simple manual trigger without inputs

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile Resume LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            Sr_Firmware_Engineer_Parth_Sanepara.tex
            CoverLetter_Parth_Sanepara.tex

      # - name: Compile CoverLetter LaTeX document
      #   uses: xu-cheng/latex-action@v3
      #   with:
      #     root_file: Parth_Sanepara_CoverLetter.tex
  

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            Sr_Firmware_Engineer_Parth_Sanepara.pdf
            CoverLetter_Parth_Sanepara.pdf

      - name: Commit build outputs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.pdf
          git commit -m "release: Auto-commit build output"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

