name: Build LaTeX document
on: [push]
jobs:
  build_latex:

    # Only run if commit message starts with "test:"
    if: startsWith(github.event.head_commit.message, 'test:')

    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This is important for accurate commit attribution
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Resume-Parth.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: Resume-Parth.pdf
      - name: Commit build outputs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Resume-Parth.pdf 
          git commit -m "release: Auto-commit build output"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
