# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Trigger after the LaTeX build workflow completes successfully
  workflow_run:
    workflows: ["Build LaTeX document"]  # Name of the LaTeX build workflow
    types:
      - completed

  # Allows manual trigger from the Actions tab
  workflow_dispatch:

# Set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: PDF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Upload the entire repository including the downloaded PDF

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
